ShuzoN/zut

- Makefile
- README.md
> makeでinstallとyarn

- index.js
- lambda.js
- slack.js
- test/lambda.test.js
- test/zutool.test.js
- zutool.js
依存pr: https://github.com/ShuzoN/zut/pull/4
やったことはタイトル通りです。
> indexに仕事ありすぎたのでファイル分割してslack, lambda, zutoolを作った

- .gitignore
- index.js
- zutool.js
> httpsパッケージのrequire忘れでzutが死ぬ

- lambda.js
- slack.js
- test/zutool.test.js
- zutool.js
ref: #19 
Before：6-20時まで表示
After：6-23時まで表示
24時（0時）はいらないという結論になった
> 20時->23時まで気圧や気圧警戒などを表示する

- index.js
> argsのチェックでundefined.includesして死ぬので直す

- temperature.js
> 気温差の表示が残念なことになっていたので修正

- index.js
#32 
ステージングにデプロイしたら怒られたので考え直した。
修正しました
> 名前かぶったときの処理で検索できない問題を直したらエラーでて怒られたので治す

- index.js
https://github.com/ShuzoN/zut/pull/37#discussion_r622663993
> locationIdが取得できなかったときにエラーになる問題を修正

- index.js
https://oystersjp.slack.com/archives/C01704F4HPX/p1619660097062500
> body -> parseBody

- .gitignore
- Makefile
- babel.config.js
- jest.config.js
- package.json
- run-zut.ts
- src/index.ts
- test/index.test.ts
- tsconfig.json
- yarn.lock
このprでやりたいこと
- typescriptのbuild
- jestでテスト
- index.tsの実行
> typescriptで動く世界線

- .github/workflows/deploy.yml
issue: https://github.com/ShuzoN/zut/issues/13
https://github.com/ShuzoN/zut/pull/52 のリベンジ
> Failed to resolve action download info. Error: Unable to resolve action actions/aws@master, repository not found
とどうも使うactionが違ったようなので公式のドキュメントに従って操作を行う
https://github.com/aws-actions/configure-aws-credentials
> aws credentialを利用して自動デプロイを実現する

- .github/workflows/deploy.yml
issue: https://github.com/ShuzoN/zut/issues/13
https://github.com/ShuzoN/zut/pull/55 のリベンジ
> to deploy revenge2

- Makefile
issue: https://github.com/ShuzoN/zut/issues/13
https://github.com/ShuzoN/zut/issues/13#issuecomment-855254666
> zipの内容がネストしてて動かないので修正

- .github/workflows/deploy.yml
issue : https://github.com/ShuzoN/zut/issues/13
s3の更新だけじゃダメでlambdaもデプロイしないと行けない
> deploy lambda

- src/Actions/helpAction.ts
- src/Actions/weatherAction.ts
- src/Types/action.ts
- src/argBody.ts
- src/index.ts
- src/lambda.ts
- src/router.ts
issue: https://github.com/ShuzoN/zut/issues/33
indexに処理書きすぎなので一旦actionレイヤを設けてrouterで出し分けるようにしたい
```
[shuzon:ins]  ~/work/zut
$ make zut/ts
/usr/local/bin/yarn install
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.44s.
/usr/local/bin/yarn run zut/ts 
yarn run v1.22.4
$ ts-node ./run-zut.ts
{
response_type: 'in_channel',
blocks: [
{
type: 'section',
text: {
type: 'mrkdwn',
text: '/zut 場所　(--tomorrow)\n' +
'対応する地名が複数ある場合は地名とcity_codeを表示します。\n' +
'天気表示は「市町村区名」のみ入力するのがコツです。\n' +
'フルネームで入れると動きません。\n' +
'\n' +
'e.g. /zut 仙台\n' +
'宮城県仙台市青葉区: 04101\n' +
'宮城県仙台市宮城野区: 04102\n' +
'宮城県仙台市泉区: 04103\n' +
'...\n' +
'\n' +
'\n' +
'e.g. /zut 仙台市青葉区\n' +
'今日の天気表示\n' +
'\n' +
'e.g. /zut 仙台市青葉区 --tomorrow\n' +
'明日の天気表示\n' +
'\n' +
'---\n' + …
```
> indexから処理を追い出す

- src/Actions/weatherAction.ts
- src/Types/locations.ts
- src/Types/utils.ts
- src/Types/zutool.ts
- src/argBody.ts
- src/zutool.ts
実行する際に0から始まるcity_code(数字)を利用すると実行エラーが出る。
numberを扱うと先頭0だと扱えない。
そのためstringで扱うようにする。
レビューポイント: 最低限の影響範囲で要件クリアしているか
- city_codeの先頭が0でも動くようにnumberからstringに変更した
- 
- 特になし
```shell
$ make test zut/ts ARG=01211
/usr/local/bin/yarn install
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.33s.
/usr/local/bin/yarn test
yarn run v1.22.4
$ jest --config ./jest.config.js
PASS  test/lambda.test.ts
PASS  test/temperature.test.ts
PASS  test/zutool.test.ts
PASS  test/weather.test.ts
PASS  test/pressure-level.test.ts
PASS  test/search.test.ts
Test Suites: 6 passed, 6 total
Tests:       17 passed, 17 total
Snapshots:   0 total
Time:        3.533 s
Ran all test suites.
✨  Done in 4.52s.
/usr/local/bin/yarn run zut/ts 01211
yarn run v1.22.4
$ ts-node ./run-zut.ts …
```
> city_codeの先頭が0でも動くように

- .github/workflows/nodejs.yml
ref: https://github.com/ShuzoN/zut/pull/26
これの会話で `毎度run/tsすんのめんどくさいな`　という話になったので追加.
前に0から始まるidが落ちたのと全角を含むと落ちる修正があったのでこちらに追加しておく
> ciでrun/tsする

- Makefile
- README.md
- package.json
- run-zut.ts
- yarn-error.log
> zutのts化完了済みなので、旧zutコマンドを削除

- src/index.ts
ref: https://github.com/ShuzoN/zut/issues/76
node16にするとエラー吐くでの一旦anyに落とす
> errorをanyにしてエラーを回避

- .github/workflows/deploy.yml
- .github/workflows/nodejs.yml
ref: https://github.com/ShuzoN/zut/issues/76
github workflowからさよなら
> node12系は使わなくなるのでサヨナラする

- .github/workflows/nodejs.yml
> workflowで利用する引数の名前まちがえてた
